development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  username: postgres
  database: game_scoring_development

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  username: postgres
  database: game_scoring_test

production:
  adapter: postgresql
  database: game_scoring_production
  pool: 5
  timeout: 5000